### ISSUE TITLE
Add Scroll-Based Slide and Fade-In Animations Using Pure CSS

### ISSUE THREAD

**Issue by LewisContreras** [LewisContreras/LewisContreras.github.io#4]
## Description
Add smooth slide and fade-in animations to elements on the portfolio when they enter the viewport. This will enhance the user experience by providing engaging and visually appealing transitions. Ensure the implementation is done purely with CSS using the `:has()` pseudo-class to detect when elements are in the viewport.

## Tasks

1. **Identify Elements for Animation**
   - Determine which sections of the portfolio will have slide and fade-in animations (e.g., project cards, headers, text sections).

2. **Define CSS Classes**
   - Create reusable CSS classes for slide-in and fade-in effects.
   - Use CSS transitions for smooth animations.

3. **Implement `:has()` Logic**
   - Apply `:has()` selectors to detect when elements come into view.
   - Example:
     ```css
     .scroll-container:has(.animated-element:in-viewport) .animated-element {
       opacity: 1;
       transform: translateY(0);
     }

     .animated-element {
       opacity: 0;
       transform: translateY(50px);
       transition: opacity 0.5s ease, transform 0.5s ease;
     }
     ```

4. **Test Animations**
   - Verify animations on different viewport sizes and devices to ensure smooth performance.
   - Ensure no animation triggers unnecessarily or breaks the layout.

5. **Fallback for Older Browsers**
   - Provide graceful degradation for browsers that do not support `:has()`.
   - Optionally use JavaScript as a fallback if required (e.g., Intersection Observer).

## Acceptance Criteria

- Elements slide and fade into view as they enter the viewport.
- Animations are smooth and do not cause layout shifts.
- No JavaScript is used for the animation logic.
- Portfolio maintains responsiveness and accessibility.
- Fallbacks are implemented for browsers without `:has()` support.

## References

- [MDN: `:has()` CSS pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/:has)
- [CSS Transitions Guide](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions)
